# Generated by Django 4.2.7 on 2026-04-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerDecision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_composition', models.JSONField()),
                ('ai_prediction', models.JSONField()),
                ('ai_recommendation', models.JSONField()),
                ('final_values', models.JSONField()),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MachineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('composition', models.JSONField()),
                ('response', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machine_log', to='predictor.managerdecision')),
            ],
        ),
    ]
