# Generated by Django 4.2.7 on 2026-04-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_previousrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousrun',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
